# Generated by Django 5.1.2 on 2024-11-25 13:49

import apps.projects.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('template_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=50, unique=True)),
                ('industry_id', models.ForeignKey(default=apps.projects.models.get_default_industry, on_delete=django.db.models.deletion.SET_DEFAULT, to='projects.industry')),
            ],
        ),
    ]
