# Generated by Django 5.1.2 on 2024-11-25 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatePhase',
            fields=[
                ('phase_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase_name', models.CharField(max_length=50)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='phases', to='projects.template')),
            ],
        ),
    ]
