# Generated by Django 5.1.2 on 2024-11-25 20:02

import apps.projects.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_templatephase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='industry_id',
            field=models.ForeignKey(default=apps.projects.models.get_default_industry, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='templates', to='projects.industry'),
        ),
    ]
