# Generated by Django 5.1.2 on 2024-11-26 13:35

import apps.projects.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_industry_industry_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='industry_id',
            field=models.ForeignKey(default=apps.projects.models.get_default_industry, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='templates', to='projects.industry', verbose_name='Industry ID'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Template ID'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Template name'),
        ),
    ]
