# Generated by Django 5.1.2 on 2024-11-26 13:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_template_industry_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatephase',
            name='phase_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Phase ID'),
        ),
        migrations.AlterField(
            model_name='templatephase',
            name='phase_name',
            field=models.CharField(max_length=50, verbose_name='Phase name'),
        ),
        migrations.AlterField(
            model_name='templatephase',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='phases', to='projects.template', verbose_name='Template'),
        ),
    ]
