# Generated by Django 5.1.2 on 2024-11-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_templatephase_phase_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='industry_id',
            new_name='industry',
        ),
    ]
