# Generated by Django 5.1.2 on 2024-12-03 10:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organization_organization_name_slug'),
        ('projects', '0009_alter_industry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the project, generated automatically.', primary_key=True, serialize=False, verbose_name='Project ID')),
                ('project_name', models.CharField(help_text='The name of the project, unique within the organization.', max_length=120, verbose_name='Project name')),
                ('project_name_slug', models.SlugField(help_text='A URL-safe slug version of the project name.', max_length=255, verbose_name='Project Name Slug')),
                ('description', models.TextField(blank=True, verbose_name='Project description')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the project was created.', verbose_name='Project creation date')),
                ('deadline', models.DateTimeField(help_text='The date and time by which the project should be completed.', verbose_name='Deadline date')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('ON_HOLD', 'ON_HOLD'), ('DONE', 'Done')], default='IN_PROGRESS', help_text='The current status of the project.', max_length=15, verbose_name='Project status')),
                ('organization', models.ForeignKey(help_text='The organization that owns or manages this project.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization', verbose_name='Project organization')),
                ('template', models.ForeignKey(help_text='The template from which this project is based.', on_delete=django.db.models.deletion.RESTRICT, to='projects.template', verbose_name='Project base template')),
            ],
        ),
    ]
