# Generated by Django 5.1.2 on 2024-12-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_customphase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(help_text='The date and time by which the project should be completed.', verbose_name='Deadline date'),
        ),
    ]
