# Generated by Django 5.1.2 on 2024-12-05 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('phase_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Phase id')),
                ('custom_phase', models.ForeignKey(help_text='Custom phase specific to this project', on_delete=django.db.models.deletion.CASCADE, to='projects.customphase', verbose_name='Custom phase')),
                ('project', models.ForeignKey(help_text='Project which this phase belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project', verbose_name='Project')),
                ('template_phase', models.ForeignKey(help_text='Project phase inheritied from a template', on_delete=django.db.models.deletion.RESTRICT, to='projects.templatephase', verbose_name='Template phase')),
            ],
        ),
    ]
