# Generated by Django 5.1.2 on 2024-12-27 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_template_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphase',
            name='custom_phase',
            field=models.ForeignKey(help_text='Custom phase specific to this project', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.customphase', verbose_name='Custom phase'),
        ),
    ]
