# Generated by Django 5.1.2 on 2024-12-27 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_projectphase_custom_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphase',
            name='template_phase',
            field=models.ForeignKey(help_text='Project phase inheritied from a template', null=True, on_delete=django.db.models.deletion.RESTRICT, to='projects.templatephase', verbose_name='Template phase'),
        ),
    ]
