# Generated by Django 5.1.2 on 2024-12-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_project_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(help_text='The name of the project, unique within the organization.', max_length=40, verbose_name='Project name'),
        ),
    ]
