# Generated by Django 5.1.2 on 2024-12-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_project_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name_slug',
            field=models.SlugField(help_text='A URL-safe slug version of the project name.', max_length=60, verbose_name='Project Name Slug'),
        ),
    ]
