# Generated by Django 5.1.2 on 2025-01-03 11:37

import pms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_project_project_name_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(default=pms.utils.base_62_pk, editable=False, help_text='A unique identifier for the project.', max_length=40, primary_key=True, serialize=False, verbose_name='Project ID'),
        ),
    ]
