# Generated by Django 5.1.2 on 2025-01-08 09:58

import pms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_projectmember_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(default=pms.utils.base_62_pk, editable=False, help_text='A unique identifier for the project.', max_length=11, primary_key=True, serialize=False, verbose_name='Project ID'),
        ),
    ]
