# Generated by Django 5.1.2 on 2025-01-08 21:23

import pms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_project_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphase',
            name='phase_id',
            field=models.CharField(default=pms.utils.base_62_pk, editable=False, max_length=11, primary_key=True, serialize=False, verbose_name='Phase id'),
        ),
    ]
