# Generated by Django 5.1.2 on 2025-02-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_projectmember_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectphase',
            name='custom_phase',
        ),
        migrations.RemoveField(
            model_name='projectphase',
            name='template_phase',
        ),
        migrations.AddField(
            model_name='projectphase',
            name='phase_name',
            field=models.CharField(default='', max_length=200, verbose_name='Phase name'),
        ),
    ]
