# Generated by Django 5.1.2 on 2025-02-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_remove_projectphase_custom_phase_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPhase',
        ),
    ]
