# Generated by Django 5.1.2 on 2025-01-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username_slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
