# Generated by Django 5.1.2 on 2025-01-06 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only, with a single space allowed between words.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter a valid username. This value may contain only letters, numbers, and @/./+/-/_ characters, with a single space allowed between words.', regex='^[\\w.@+-]+(?: [\\w.@+-]+)*\\Z')], verbose_name='username'),
        ),
    ]
