# Generated by Django 5.1.2 on 2025-01-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default='DEFAULTPROFILEPICTURE', help_text='Name of the profile picture in S3 bucket', max_length=255),
        ),
    ]
