# Generated by Django 5.1.2 on 2024-11-19 10:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Organization ID')),
                ('organization_name', models.CharField(max_length=50, unique=True, verbose_name='Organization name')),
                ('organization_password', models.CharField(max_length=255, verbose_name='Organization password')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
            ],
        ),
    ]
