# Generated by Django 5.1.2 on 2024-11-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_rename_organizationmembers_organizationmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_name_slug',
            field=models.SlugField(default='', max_length=100, verbose_name='Organization Slug'),
        ),
    ]
