# Generated by Django 5.1.2 on 2025-01-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_organization_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member')], default='Member', max_length=50),
        ),
    ]
