# Generated by Django 5.1.2 on 2024-12-31 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0020_alter_project_project_name_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCollection',
            fields=[
                ('collection_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Collection ID')),
                ('collection_name', models.CharField(db_comment='Collection name unique in the phase of the project', max_length=100, verbose_name='Task name')),
                ('project_phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectphase')),
            ],
        ),
    ]
