# Generated by Django 5.1.2 on 2024-12-31 10:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Task ID')),
                ('task_name', models.CharField(db_comment='Task name unique within a task collection', max_length=30, verbose_name='Task name')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Start date')),
                ('deadline', models.DateField(verbose_name='Deadline data')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('ON_HOLD', 'ON_HOLD'), ('DONE', 'Done')], default='IN_PROGRESS', help_text='The current status of the task.', max_length=15, verbose_name='Task status')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.taskcollection')),
            ],
        ),
    ]
