# Generated by Django 5.1.2 on 2024-12-31 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_project_project_name_slug'),
        ('tasks', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcollection',
            name='project_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_collections', to='projects.projectphase'),
        ),
    ]
