# Generated by Django 5.1.2 on 2025-01-08 13:04

import pms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcollection',
            name='collection_id',
            field=models.CharField(default=pms.utils.base_62_pk, editable=False, max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='Collection ID'),
        ),
    ]
