# Generated by Django 5.1.2 on 2025-01-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='collection',
        ),
        migrations.DeleteModel(
            name='TaskCollection',
        ),
    ]
