# Generated by Django 5.1.2 on 2025-01-09 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_projectphase_phase_id'),
        ('tasks', '0009_remove_task_collection_delete_taskcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_phase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='phase_tasks', to='projects.projectphase'),
        ),
    ]
