# Generated by Django 5.1.2 on 2025-01-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_taskassignment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(db_comment='Task name unique within a task collection', max_length=100, verbose_name='Task name'),
        ),
    ]
